[package]
name = "databend-common-proto-conv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
chrono = { workspace = true }
chrono-tz = { workspace = true, features = ["serde"] }
databend-common-expression = { workspace = true }
databend-common-io = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-protos = { workspace = true }
enumflags2 = { workspace = true }
minitrace = { workspace = true }
num = "0.4.0"
prost = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]

[dev-dependencies]
anyhow = { workspace = true }
convert_case = { version = "0.6.0" }
maplit = "1.0.2"
pretty_assertions = "1.3.0"

[lints]
workspace = true
