[package]
name = "databend-common-config"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = true

[features]
default = []
storage-hdfs = ["databend-common-storage/storage-hdfs"]

[package.metadata.cargo-machete]
ignored = ["strum"]

[dependencies]
chrono-tz = { workspace = true }
clap = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-grpc = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-tracing = { workspace = true }
log = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serfig = { workspace = true }
strum = "0.24.1"

[dev-dependencies]
pretty_assertions = "1.3.0"

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true
