[package]
name = "databend-common-grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
anyerror = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
hickory-resolver = "0.24"
hyper = "0.14.20"
jwt-simple = "0.11.0"
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[build-dependencies]

[features]
mocks = []

[lints]
workspace = true
