[package]
name = "databend-common-ast"
version = "0.0.2"
publish = true
description = "SQL parser for Databend"
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = "https://github.com/datafuselabs/databend/tree/main/src/query/ast"

[lib]
doctest = false

[dependencies]
derive-visitor = { workspace = true }
enum-as-inner = "0.5.1"
ethnum = { workspace = true }
fast-float = "0.2.0"
indent = "0.1.1"
itertools = { workspace = true }
logos = "0.12.1"
minitrace = { workspace = true }
nom = "7.1.1"
nom-rule = "0.3.1"
ordered-float = { workspace = true }
pratt = "0.4.0"
pretty = "0.11.3"
pretty_assertions = "1.3.0"
recursive = "0.1.1"
rspack-codespan-reporting = "0.11"
serde = { workspace = true }
serde_json = { workspace = true }
strsim = "0.10"
strum = "0.24"
strum_macros = "0.24"
unindent = "0.2.3"
url = "2.3.1"

[dev-dependencies]
criterion = { workspace = true }
goldenfile = "1.4"
regex = { workspace = true }

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
