[package]
name = "databend-common-management"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
async-backtrace = { workspace = true }
async-trait = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-functions = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-store = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-proto-conv = { workspace = true }
enumflags2 = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
prost = { workspace = true }
serde = "1.0.150"
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
databend-common-expression = { workspace = true }
databend-common-meta-embedded = { workspace = true }
databend-common-storage = { workspace = true }
mockall = "0.11.2"

[lints]
workspace = true
