[package]
name = "databend-common-hashtable"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
databend-common-arrow = { workspace = true }
databend-common-base = { workspace = true }
## Must disable feature "runtime-rng", it will make the hash results unstable in cluster
ahash = { version = "0.8.2", features = ["no-rng"] }
bumpalo = { workspace = true }
cfg-if = "1.0.0"
ethnum = { workspace = true }
ordered-float = { workspace = true, features = ["serde"] }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
