[package]
name = "databend-storages-common-index"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[package.metadata.cargo-machete]
ignored = ["xorfilter-rs", "match-template"]

[dependencies]
anyerror = { workspace = true }
cbordata = { version = "0.6.0" }
crc32fast = "1.3.2"
databend-common-arrow = { workspace = true }
databend-common-ast = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-functions = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
match-template = { workspace = true }
minitrace = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
tantivy-common = "0.7.0"
thiserror = { workspace = true }
xorfilter-rs = { workspace = true, features = ["cbordata"] }

[dev-dependencies]
criterion = { workspace = true }
databend-common-arrow = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "build_from_block"
harness = false

[lints]
workspace = true
