[package]
name = "databend-common-meta-api"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = true

[dependencies]
anyhow = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-stoerr = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-proto-conv = { workspace = true }
enumflags2 = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
