[package]
name = "databend-meta"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = ["simd", "memory-profiling"]
memory-profiling = ["databend-common-base/memory-profiling", "databend-common-http/memory-profiling"]
simd = ["databend-common-arrow/simd"]
io-uring = [
    "sled/io_uring",
    "databend-common-meta-sled-store/io-uring",
    "databend-common-meta-raft-store/io-uring",
]

[dependencies]
anyerror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
backon = "0.4"
clap = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-base = { workspace = true }
databend-common-grpc = { workspace = true }
databend-common-http = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-client = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-raft-store = { workspace = true }
databend-common-meta-sled-store = { workspace = true }
databend-common-meta-stoerr = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-metrics = { workspace = true }
databend-common-tracing = { workspace = true }
deepsize = { workspace = true }
derive_more = { workspace = true }
feature-set = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
logcall = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
poem = { workspace = true }
prometheus-client = "0.22"
prost = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = { workspace = true }
sled = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

[dev-dependencies]
env_logger = "0.10.0"
maplit = "1.0.2"
pretty_assertions = "1.3.0"
regex = { workspace = true }
reqwest = { workspace = true }
temp-env = "0.3.0"
tempfile = "3.4.0"
test-harness = "0.1.1"

[build-dependencies]
databend-common-building = { workspace = true }

[lints]
workspace = true
