name: "Test Stateful Sharing"
description: "Running stateful with sharing in standalone mode"
inputs:
  target:
    description: 'the rust target to build'
    required: false
    default: x86_64-unknown-linux-gnu

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_bendsql

    - uses: dtolnay/rust-toolchain@stable
      id: toolchain
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: Minio Setup for (ubuntu-latest only)
      shell: bash
      run: |
        docker run -d --network host --name minio \
                -e "MINIO_ACCESS_KEY=minioadmin" \
                -e "MINIO_SECRET_KEY=minioadmin" \
                -e "MINIO_ADDRESS=:9900" \
                -v /tmp/data:/data \
                -v /tmp/config:/root/.minio \
                minio/minio server /data

        export AWS_ACCESS_KEY_ID=minioadmin
        export AWS_SECRET_ACCESS_KEY=minioadmin
        export AWS_EC2_METADATA_DISABLED=true

        aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://provider-bucket
        aws --endpoint-url http://127.0.0.1:9900/ s3 mb s3://consumer-bucket
    - name: Run integration Share database Tests with Standalone mode
      shell: bash
      run: |
        ./scripts/ci/ci-run-share-tests.sh
