[package]
name = "databend-common-meta-raft-store"
description = "Raft state machine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
io-uring = ["databend-common-meta-sled-store/io-uring"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
databend-common-base = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-grpc = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-sled-store = { workspace = true }
databend-common-meta-stoerr = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-tracing = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
futures-async-stream = { workspace = true }
futures-util = { workspace = true }
hostname = "0.3.1"
itertools = { workspace = true }
log = { workspace = true }
maplit = "1.0.2"
minitrace = { workspace = true }
num = "0.4.0"
openraft = { workspace = true }
ordq = { workspace = true }
rotbl = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stream-more = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
databend-common-base = { workspace = true }
pretty_assertions = "1.3.0"
tempfile = "3.4.0"
test-harness = "0.1.1"
tokio = { workspace = true }

[lints]
workspace = true
