[package]
name = "databend-common-catalog"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
databend-common-arrow = { workspace = true }
databend-common-base = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-io = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-store = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-settings = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-users = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
databend-storages-common-txn = { workspace = true }
dyn-clone = "1.0.9"
log = { workspace = true }
parking_lot = { workspace = true }
parquet = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
thrift = "0.17.0"
typetag = { workspace = true }
xorf = { version = "0.11.0", default-features = false, features = ["binary-fuse"] }

[dev-dependencies]
goldenfile = "1.4"

[lints]
workspace = true
