[package]
name = "databend-common-meta-types"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[dependencies]
anyerror = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-meta-stoerr = { workspace = true }
databend-common-tracing = { workspace = true }
deepsize = { workspace = true }
derive_more = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
openraft = { workspace = true }
prost = { workspace = true }
rotbl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
databend-common-building = { workspace = true }
prost-build = { workspace = true }
tonic-build = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
regex = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["num-derive", "prost"]

[lints]
workspace = true
