[package]
name = "databend-common-meta-embedded"
description = "distributed meta data service"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
io-uring = ["databend-common-meta-sled-store/io-uring", "databend-common-meta-raft-store/io-uring"]

[dependencies]
async-trait = { workspace = true }
databend-common-base = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-kvapi = { workspace = true }
databend-common-meta-raft-store = { workspace = true }
databend-common-meta-sled-store = { workspace = true }
databend-common-meta-stoerr = { workspace = true }
databend-common-meta-types = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
tempfile = "3.4.0"

[dev-dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
