[package]
name = "databend-common-script"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
databend-common-ast = { workspace = true }
databend-common-exception = { workspace = true }
derive-visitor = { workspace = true }
minitrace = { workspace = true }

[dev-dependencies]
goldenfile = "1.4"
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "sync"] }
unindent = "0.2.3"

[lints]
workspace = true
