name: "Test Stateful Standalone Iceberg Rest"
description: "Running Stateful Iceberg Rest tests in standalone mode"
inputs:
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup_bendsql
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Iceberg Rest Setup for (ubuntu-latest only)
      shell: bash
      run: |
        docker-compose -f "./docker/it-iceberg-rest/docker-compose.yaml" up --quiet-pull -d

    - name: Run Stateful Tests with Standalone mode
      shell: bash
      run: |
        ./scripts/ci/ci-run-stateful-iceberg-rest-tests-standalone.sh
