[package]
name = "databend-common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-backtrace = { workspace = true }
base64 = "0.22"
bytes = { workspace = true }
databend-common-auth = { workspace = true }
databend-common-base = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-meta-api = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-users = { workspace = true }
http = { workspace = true }
log = { workspace = true }
moka = "0.12"
opendal = { workspace = true }
reqwest = { workspace = true }
ring = "0.16.20"
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
